import type {GetStaticProps, NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = (users : any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {JSON.stringify(users)}
</div>
  )
}

export const getStaticProps : GetStaticProps = async (context) => {

    const res = await fetch("http://localhost:3002/api/user")
    const users = await res.json();

    return {
        props : {
            user : users
        }
    }
}

export default Home
